// Сгенерировано scripts/gen-jupiter-employers.mjs из scripts/career-sites.tsv — не править руками.
export const JUPITER_EMPLOYERS: [name: string, host: string][] = [
  ["1С", "1c.ru"],
  ["1С-Битрикс", "careers.bitrix24.ru"],
  ["2ГИС", "job.2gis.ru"],
  ["585 Золотой", "rabota.585zolotoy.ru"],
  ["А101", "a101.ru"],
  ["Абсолют Банк", "absolutbank.ru"],
  ["Авиасейлс", "aviasales.ru"],
  ["Авилон", "rabota.avilon.ru"],
  ["Автодок", "autodoc.ru"],
  ["Автодом", "avtodom.ru"],
  ["Автомир", "avtomir.ru"],
  ["Адвантум", "advantum.ru"],
  ["Азбука вкуса", "av.ru"],
  ["Ай-Теко", "i-teco.ru"],
  ["Айти Новация", "itnovation.pro"],
  ["Айтуби", "it2bsns.ru"],
  ["Алмаз-Антей", "almaz-antey.ru"],
  ["Альфа-Банк", "job.alfabank.ru"],
  ["АльфаСтрахование", "alfastrah.ru"],
  ["АМ Винотеки", "amwine.ru"],
  ["Аптека Апрель", "apteka-april.ru"],
  ["АТОЛ", "career.atol.ru"],
  ["Аурига", "hr.auriga.ru"],
  ["Ашан", "auchan.ru"],
  ["Аэрофлот", "vacancy.aeroflot.ru"],
  ["Аэроэкспресс", "aeroexpress.ru"],
  ["Б1", "b1.ru"],
  ["Базис", "basistech.ru"],
  ["Байкал Сервис", "baikalsr.ru"],
  ["Балтика", "career.baltika.ru"],
  ["Банк ДОМ.РФ", "domrfbank.ru"],
  ["Банк Зенит", "zenit.ru"],
  ["Банк Русский Стандарт", "rsb.ru"],
  ["Банк Синара", "sinara.ru"],
  ["Банки.ру", "banki.ru"],
  ["Билайн", "job.beeline.ru"],
  ["БИОКАД", "career.biocad.ru"],
  ["Братья Караваевы", "karavaevi.ru"],
  ["Бристоль", "bristol.ru"],
  ["Будь Здоров", "bud-zdorov.ru"],
  ["БФТ-Холдинг", "bft.ru"],
  ["ВБЦ", "vbankcenter.ru"],
  ["ВДНХ", "vdnh.ru"],
  ["Верный", "verno-info.ru"],
  ["Винлаб", "winelab.ru"],
  ["ВкусВилл", "vkusvill.ru"],
  ["Вкусно", "rabotaitochka.ru"],
  ["Внуково", "vnukovo.ru"],
  ["Волконский", "wolkonsky.com"],
  ["ВсеИнструменты.ру", "vseinstrumenti.ru"],
  ["ВСК", "vsk.ru"],
  ["ВТБ", "rabota-vtb.ru"],
  ["Газпром", "gazprom.ru"],
  ["Газпром нефть", "career.gazprom-neft.ru"],
  ["Газпром-Медиа", "gazprom-media.com"],
  ["Газпромбанк", "gazprombank.tech"],
  ["Галактика", "galaktika.ru"],
  ["Галамарт", "galamart.ru"],
  ["Гараж 8", "garage-eight.com"],
  ["Гемотест", "gemotest.ru"],
  ["Герофарм", "geropharm.ru"],
  ["Глобус", "rabota.globus.ru"],
  ["ГНИВЦ", "career.gnivc.ru"],
  ["Горздрав", "gorzdrav.org"],
  ["Грабли", "grably.ru"],
  ["Гранель", "granelle.ru"],
  ["Группа Астра", "astra.ru"],
  ["Группа ЛСР", "lsr.ru"],
  ["ГУМ", "gum.ru"],
  ["ДатаРу", "dataru.ru"],
  ["Делимобиль", "delimobil.ru"],
  ["Деловые Линии", "job.dellin.ru"],
  ["Дельта Компьютерс", "deltacomputers.ru"],
  ["Детский мир", "jobs.detmir.ru"],
  ["Дзен", "dzen.ru"],
  ["Диасофт", "diasoft.ru"],
  ["ДИКСИ", "dixy.ru"],
  ["Додо Пицца", "rabotavdodo.ru"],
  ["ДОМ.РФ", "xn--d1aqf.xn--p1ai"],
  ["Домодедово", "business.dme.ru"],
  ["Донстрой", "donstroy.moscow"],
  ["ЕАПТЕКА", "eapteka.ru"],
  ["ЕВРАЗ", "evraz.com"],
  ["ЕвроХим", "eurochemgroup.com"],
  ["Золотое Яблоко · /", "job.goldapple.ru"],
  ["Иви", "corp.ivi.ru"],
  ["Инвитро", "invitro.ru"],
  ["Ингосстрах", "ingos.ru"],
  ["Инград", "ingrad.ru"],
  ["Индасофт", "indusoft.ru"],
  ["Институт «Стрелка»", "strelka.com"],
  ["Интер РАО", "interrao.ru"],
  ["Информзащита", "infosec.ru"],
  ["Инфосистемы Джет", "jet.su"],
  ["ИнфоТеКС", "career.infotecs.ru"],
  ["История будущего", "futurehistory.ru"],
  ["ИТЭЛМА", "itelma.ru"],
  ["Кант", "kant.ru"],
  ["Карма Групп", "karma-group.ru"],
  ["КАРО", "karofilm.ru"],
  ["КБК «Черёмушки»", "kf-tort.ru"],
  ["Когнитивные системы", "cogsys.company"],
  ["Код Безопасности", "securitycode.ru"],
  ["Коломенский", "kolomenskiy.ru"],
  ["Контакт", "itcontact.ru"],
  ["Контур", "kontur.ru"],
  ["КОРУС Консалтинг", "career.korusconsulting.ru"],
  ["Кофемания", "rabota.coffeemania.ru"],
  ["Красное&Белое", "krasnoeibeloe.ru"],
  ["КРОК", "careers.croc.ru"],
  ["Крокус", "crocus-group.ru"],
  ["Купер", "kuper.ru"],
  ["Л'Этуаль", "letu.ru"],
  ["Лабиринт", "labirint.org"],
  ["Ланит", "lanit.ru"],
  ["Лемана ПРО", "rabota.lemanapro.ru"],
  ["Лента", "career.lenta.com"],
  ["Литрес", "litres.ru"],
  ["Локо-Банк", "lockobank.ru"],
  ["Лоция", "loodsen.ru"],
  ["Лужники", "luzhniki.ru"],
  ["Лукойл", "lukoil.ru"],
  ["М.Видео-Эльдорадо", "career.mvideoeldorado.ru"],
  ["Магнит", "rabota.magnit.ru"],
  ["Магнолия", "mgnl.ru"],
  ["Мария-Ра", "maria-ra.ru"],
  ["Мать и дитя", "mamadeti.ru"],
  ["МГТС", "mgts.ru"],
  ["Мегамаркет", "megamarket.ru"],
  ["МегаФон · /", "job.megafon.ru"],
  ["Медси", "medsi.ru"],
  ["Металлоинвест", "metalloinvest.com"],
  ["Мираторг", "miratorg.ru"],
  ["МКБ", "mkb.ru"],
  ["ММК", "mmk.ru"],
  ["Много Мебели", "mnogomebeli.com"],
  ["Модульбанк", "modulbank.ru"],
  ["МойСклад", "moysklad.ru"],
  ["Монетка", "career.monetka.ru"],
  ["Монополия", "monopoly.online"],
  ["Мосводоканал", "mosvodokanal.ru"],
  ["Мосгаз", "mosgaz.ru"],
  ["Мосгортранс", "mosgortrans.ru"],
  ["Мосинжпроект", "mosinzhproekt.ru"],
  ["Москвич", "recruitment.moskvich.ru"],
  ["Московская биржа", "moex.com"],
  ["Московская пивоваренная компания", "mpbc.ru"],
  ["Московский метрополитен", "mosmetro.ru"],
  ["Мостотрест", "mostotrest.ru"],
  ["Мострансавто", "mostransavto.ru"],
  ["Мосэнерго", "mosenergo.gazprom.ru"],
  ["МОЭК", "moek.ru"],
  ["МТС", "job.mts.ru"],
  ["МТС Банк", "mtsbank.ru"],
  ["Му-Му", "cafemumu.ru"],
  ["Мултон Партнерс", "multonpartners.ru"],
  ["Наумен", "naumen.ru"],
  ["Национальная Медиа Группа", "nmg.ru"],
  ["Неофарм", "neopharm.ru"],
  ["Неофлекс", "neoflex.ru"],
  ["Нетология", "netology.ru"],
  ["НЛМК", "nlmk.com"],
  ["Новатэк", "novatek.ru"],
  ["Новикомбанк", "novikom.ru"],
  ["Норбит", "norbit.ru"],
  ["Норникель", "career.nornickel.ru"],
  ["НСПК", "nspk.ru"],
  ["О'КЕЙ", "okmarket.ru"],
  ["ОАК", "uacrussia.ru"],
  ["Объединённые кондитеры", "uniconf.ru"],
  ["Орматек", "ormatek.com"],
  ["Останкинский мясоперерабатывающий комбинат", "ompk.ru"],
  ["Островок", "career.ostrovok.ru"],
  ["ОТП Банк", "otpbank.ru"],
  ["Палиндром", "palindrome.media"],
  ["Пачка", "pachca.com"],
  ["ПГК", "pgk.ru"],
  ["Перекрёсток", "rabota.perekrestok.ru"],
  ["Петрович", "petrovichjob.ru"],
  ["ПИК", "pik.ru"],
  ["Планета Здоровья", "planetazdorovo.ru"],
  ["Победа", "flypobeda.ru"],
  ["Подружка", "rabotavpodrygke.ru"],
  ["Поехали", "poehali.dev"],
  ["Полюс", "career.polyus.com"],
  ["Почта Банк", "pochtabank.ru"],
  ["Почта России", "pochta.ru"],
  ["Протей", "protei.ru"],
  ["Протек", "protek.ru"],
  ["Профи.ру", "profi.ru"],
  ["ПСБ", "psbank.ru"],
  ["Пульс", "puls.ru"],
  ["ПЭК", "hr.pecom.ru"],
  ["Пятёрочка", "rabota5ka.ru"],
  ["Р-Фарм", "r-pharm.com"],
  ["Райффайзенбанк", "career.raiffeisen.ru"],
  ["Ранколл", "runcall.ru"],
  ["РБК", "rbc.ru"],
  ["РДВ Технолоджи", "rdwcomp.ru"],
  ["Ренессанс Кредит", "rencredit.ru"],
  ["Ренессанс страхование", "renins.ru"],
  ["РЕСО-Гарантия", "reso.ru"],
  ["РЖД", "team.rzd.ru"],
  ["РИВ ГОШ", "rivegauche.ru"],
  ["Ригла", "rigla.ru"],
  ["Рольф", "rolf.ru"],
  ["Росатом", "rosatom-career.ru"],
  ["Росбанк", "rosbank.ru"],
  ["Росгосстрах", "rgs.ru"],
  ["Роскосмос", "roscosmos.ru"],
  ["Роснефть", "rosneft.ru"],
  ["Россельхозбанк", "rshb.ru"],
  ["Россети Московский регион", "rossetimr.ru"],
  ["Ростелеком", "job.rt.ru"],
  ["Ростех", "rostec.ru"],
  ["РТК-ЦОД", "rt-dc.ru"],
  ["Русагро", "rusagrogroup.ru"],
  ["РУСАЛ", "rusal.ru"],
  ["РусГидро", "rushydro.ru"],
  ["С-Терра", "s-terra.ru"],
  ["Самокат · /", "vacancy.samokat.ru"],
  ["Самолет", "samolet.ru"],
  ["Сбер · /", "rabota.sber.ru"],
  ["СберЗдоровье", "sberhealth.ru"],
  ["Северсталь", "career.severstal.com"],
  ["Селектел", "selectel.ru"],
  ["Семейный доктор", "fdoctor.ru"],
  ["СИБУР", "career.sibur.ru"],
  ["Синергия", "synergy.ru"],
  ["Синимекс", "cinimex.ru"],
  ["Ситилинк", "job.citilink.ru"],
  ["Слата", "slata.ru"],
  ["СМ-Клиника", "smclinic.ru"],
  ["СМП Банк", "smpbank.ru"],
  ["Снежная Королева", "snowqueen.ru"],
  ["Совкомбанк", "sovcombank.ru"],
  ["СОГАЗ", "sogaz.ru"],
  ["Согласие", "soglasie.ru"],
  ["Солар", "team.rt-solar.ru"],
  ["Спортмастер · /", "job.sportmaster.ru"],
  ["Спортс", "sports.ru"],
  ["Сравни", "career.sravni.ru"],
  ["Столички", "stolichki.ru"],
  ["Суши Wok", "sushiwok.ru"],
  ["Т-Банк · /career/vacancies/it", "tbank.ru"],
  ["Т1", "career.t1.ru"],
  ["Тактика", "taktikagames.ru"],
  ["Тануки", "job.tanuki.ru"],
  ["Твоё", "tvoe.ru"],
  ["Твой Дом", "tvoydom.ru"],
  ["Тензор", "tensor.ru"],
  ["Теремок", "rabota.teremok.ru"],
  ["Техвилл", "techvill.ru"],
  ["Технологии Доверия", "tedo.ru"],
  ["ТК КИТ", "tk-kit.ru"],
  ["ТК Энергия", "nrg-tk.pro"],
  ["ТМК", "tmk-group.ru"],
  ["Точка Банк", "hr.tochka.com"],
  ["Траектория технологий", "trctech.ru"],
  ["ТрансКонтейнер", "trcont.com"],
  ["Транснефть", "transneft.ru"],
  ["ТТК Диджитал", "tattelecom.digital"],
  ["Туту", "c.tutu.ru"],
  ["Улыбка радуги", "rabota.r-ulybka.ru"],
  ["Умназия", "umnazia.ru"],
  ["Умскул", "umschool.net"],
  ["Уралкалий", "uralkali.com"],
  ["Уралсиб", "uralsib.ru"],
  ["Утконос", "utkonos.ru"],
  ["Учи.ру", "uchi.ru"],
  ["Фоксфорд", "foxford.ru"],
  ["Формула Кино", "formulakino.ru"],
  ["ФосАгро", "phosagro.ru"],
  ["ФСК", "fsk.ru"],
  ["Хеликс", "helix.ru"],
  ["Хлеб Насущный", "hlebnasushny.ru"],
  ["Хоулмонт", "job.haulmont.ru"],
  ["Циан", "krasnodar.cian.ru"],
  ["ЦППК", "central-ppk.ru"],
  ["ЦУМ", "tsum.ru"],
  ["ЦФТ", "job.cft.ru"],
  ["Чайхона №1", "chaihona.ru"],
  ["Черкизово", "vacancies.cherkizovo.com"],
  ["Черноголовка", "chernogolovka.com"],
  ["Чижик", "chizhik.club"],
  ["Читай-город", "rabota.chitai-gorod.ru"],
  ["Шереметьево", "job.svo.su"],
  ["Шинсервис", "shinservice.ru"],
  ["Шоколадница", "regions.shoko.ru"],
  ["Эвотор", "evotor.ru"],
  ["Экономический Олимп", "economolymp.ru"],
  ["Эксмо", "eksmo.ru"],
  ["Экспобанк", "expobank.ru"],
  ["ЭР-Телеком", "job.ertelecom.ru"],
  ["Эталон", "etalongroup.ru"],
  ["ЭФКО", "efko.ru"],
  ["Югория-Жизнь", "ugorialife.ru"],
  ["Юзтех", "usetech.ru"],
  ["ЮниКредит Банк", "unicreditbank.ru"],
  ["ЮТэйр", "utair.ru"],
  ["Якитория", "yakitoria.ru"],
  ["Яков и Партнёры", "yakov.partners"],
  ["Яндекс · /jobs", "yandex.ru"],
  ["Яндекс Крауд", "crowd.yandex.ru"],
  ["Ярче!", "xn--80aacr7bjeo1cwe.xn--p1ai"],
  ["Advert School", "advert.school"],
  ["Agima", "agima.ru"],
  ["amoCRM", "amocrm.ru"],
  ["Angara Security", "angarasecurity.ru"],
  ["Arenadata", "career.arenadata.tech"],
  ["Artezio", "artezio.ru"],
  ["Askona", "askona.ru"],
  ["Aston", "career.astondevs.ru"],
  ["Avito", "career.avito.com"],
  ["Axenix", "axenix.pro"],
  ["AZIMUT Hotels", "azimuthotels.com"],
  ["Azoft", "azoft.ru"],
  ["Baum", "baum.ru"],
  ["Befree", "befree.ru"],
  ["Beget", "beget.com"],
  ["Bell Integrator", "bellintegrator.ru"],
  ["BI.ZONE", "bi.zone"],
  ["BINOM", "binom.systems"],
  ["Boxberry", "boxberry.ru"],
  ["BSL", "bsl.dev"],
  ["Burger King Россия", "burgerkingrus.ru"],
  ["CDEK", "rabota.cdek.ru"],
  ["Centicore Group", "centicore.ru"],
  ["Cloud Networks", "cloudnetworks.ru"],
  ["Cloud.ru", "cloud.ru"],
  ["CMD", "cmd-online.ru"],
  ["Coffee Like", "coffee-like.com"],
  ["Cofix", "cofix.global"],
  ["Concept Club", "concept-club.ru"],
  ["Cool.Club", "cool.club"],
  ["Coral", "coral.tech"],
  ["Cosmos Hotel Group", "cosmosgroup.ru"],
  ["Crosstech", "crosstech.ru"],
  ["DDX Fitness", "ddxfitness.ru"],
  ["Deloitte", "careers.delret.ru"],
  ["Desport", "desport.ru"],
  ["Digital Design", "digdes.ru"],
  ["Directum", "career.directum.ru"],
  ["DNS", "dns-shop.ru"],
  ["DPD Россия", "dpd.ru"],
  ["Eduson", "eduson.tv"],
  ["Effective Technologies", "career.effective-group.ru"],
  ["EgeHack", "egehack.com"],
  ["EMC", "emcmos.ru"],
  ["Emex", "emex.ru"],
  ["English Yo", "englishyopta.com"],
  ["Evercode Lab", "evercodelab.ru"],
  ["Exist", "exist.ru"],
  ["Extyl", "extyl-pro.ru"],
  ["F.A.C.C.T.", "f6.ru"],
  ["Familia", "famil.ru"],
  ["Fix Price", "fix-price.com"],
  ["FM Logistic", "fmlogistic.ru"],
  ["Ginza Project", "job.ginza.ru"],
  ["Globus IT", "globus-ltd.ru"],
  ["Gloria Jeans", "lookbook.gloria-jeans.ru"],
  ["Gossip Inc.", "thegossip.app"],
  ["GRASS", "job.thgrass.com"],
  ["H2O", "h2oclean.ru"],
  ["HENDERSON", "henderson.ru"],
  ["Hoff", "job.hoff.ru"],
  ["Holy Corn", "holycorn.ru"],
  ["IBS", "ibs.ru"],
  ["IBS Appline", "appline.ru"],
  ["iFellow", "ifellow.ru"],
  ["Inline Group", "inlinegroup.ru"],
  ["iSpring", "ispring.ru"],
  ["IT_One", "it-one.ru"],
  ["ITG", "itglobal.com"],
  ["Just AI", "careers.just-ai.com"],
  ["kari", "kari.com"],
  ["Kaspersky", "careers.kaspersky.ru"],
  ["KDL", "kdl.ru"],
  ["Kefir", "kefirgames.ru"],
  ["Kept", "kept.ru"],
  ["kokos group", "career.kokocgroup.ru"],
  ["Koronatech", "koronatech.ru"],
  ["Lamoda", "job.lamoda.ru"],
  ["Lesta Games", "join.lesta.team"],
  ["Level Group", "job.level.ru"],
  ["Linx", "linx.ru"],
  ["M2 Tech", "tech.m2.ru"],
  ["Macroscop", "pro.macroscop.com"],
  ["MadMed.Media", "madmed.media"],
  ["Magic Factory Animation", "magicfactory.ru"],
  ["Major Auto", "major-auto.ru"],
  ["Major Express", "major-express.ru"],
  ["Marks Academy", "marks-academy.ru"],
  ["MedEQ", "medeq.ru"],
  ["Melon Fashion Group", "melonfashion.ru"],
  ["METRO", "rabota.metro-cc.ru"],
  ["MIND Software", "mindsw.io"],
  ["Mish", "mish.design"],
  ["MR Group", "mr-group.ru"],
  ["Navio", "navio.auto"],
  ["NeuroCity", "neuro-city.ru"],
  ["Notamedia", "nota.media"],
  ["Novikov Group", "novikovgroup.ru"],
  ["NX Studio", "studionx.ru"],
  ["O'STIN", "job.ostin.com"],
  ["Okko", "okko.tv"],
  ["Orion soft", "career.orionsoft.ru"],
  ["Oxygen", "oxygen.cloud"],
  ["Ozon", "career.ozon.ru"],
  ["Pandy", "pandy.mobi"],
  ["Performance Lab", "performance-lab.ru"],
  ["PIX Robotics", "pix.ru"],
  ["Positive Technologies", "ptsecurity.com"],
  ["PrideInBrains", "prideinbrains.com"],
  ["Prime", "promo.prime-star.ru"],
  ["Proscom", "proscom.ru"],
  ["R.S.V.P", "rsvp-agency.com"],
  ["Rambler&Co", "rambler-co.ru"],
  ["re:Store", "re-store.ru"],
  ["RedLab", "redlab.dev"],
  ["Redmadrobot", "redmadrobot.com"],
  ["REG.RU", "reg.ru"],
  ["Reksoft", "career.reksoft.com"],
  ["Rendez-Vous", "rendez-vous.ru"],
  ["ROSTIC'S", "rostics.ru"],
  ["Rubius", "rubius.com"],
  ["Rush Agency", "rush-agency.ru"],
  ["RUTUBE", "rutube.ru"],
  ["S7 Airlines", "s7.ru"],
  ["SearchInform", "searchinform.ru"],
  ["Sela", "sela.ru"],
  ["Selecty", "selecty.ru"],
  ["SETTERS", "setters.agency"],
  ["SharpLase", "sharplase.ru"],
  ["shishki.collective", "shishki.co"],
  ["SimbirSoft", "simbirsoft.com"],
  ["Simple", "simple.ru"],
  ["Skillbox", "skillbox.ru"],
  ["Skyeng", "vacancies.skyeng.ru"],
  ["SmartDec", "smartdec.net"],
  ["Softline", "softline.ru"],
  ["SPAR", "myspar.ru"],
  ["Spirit. Fitness", "career.spiritfit.ru"],
  ["Spotware Systems", "spotware.applytojob.com"],
  ["Stars Coffee", "starscoffee.ru"],
  ["START", "start.ru"],
  ["Stepik", "welcome.stepik.org"],
  ["SUNLIGHT", "job.sunlight.net"],
  ["Surf", "career.surf.ru"],
  ["t2", "msk.t2.ru"],
  ["TalkBank", "talkbank.io"],
  ["Targem Games", "targem.ru"],
  ["TerraLink", "terralink.ru"],
  ["Tilda Publishing", "company.tilda.ru"],
  ["Timeweb", "timeweb.com"],
  ["TIQUM", "techinform.pro"],
  ["Twinby", "twinby.ru"],
  ["UMA", "umastyle.app"],
  ["UPSIDE", "upside.pro"],
  ["UserGate", "usergate.com"],
  ["VK", "team.vk.company"],
  ["volna.digital", "volna.digital"],
  ["Weborama", "wbrm.ru"],
  ["White Rabbit Family", "whiterabbitfamily.ru"],
  ["Whoosh", "whoosh-bike.ru"],
  ["Wildberries / РВБ", "career.rwb.ru"],
  ["World Class", "worldclass.ru"],
  ["Wunder Fund", "wunderfund.io"],
  ["X-Fit", "xfit.ru"],
  ["X5 Group", "rabota.x5.ru"],
  ["X5 Tech", "x5.tech"],
  ["Yadro", "careers.yadro.com"],
  ["YoloPrice", "yoloprice.com"],
];
